// Generated by dartify

import 'dart:js_interop';

@JS('ol.events.Event')
@staticInterop
class Event {
  external factory Event(JSObject? opt_options);
}

extension EventExtension on Event {
  external JSString get type;
  external set type(JSString value);
  external JSObject get target;
  external set target(JSObject value);
  external void preventDefault();
  external void stopPropagation();
}

