// Generated by dartify

import 'dart:js_interop';

@JS('ol.proj.addCoordinateTransforms')
external void addCoordinateTransforms(JSObject source, JSObject destination, JSObject forward, JSObject inverse);

