// Generated by dartify

import 'dart:js_interop';

@JS('ol.proj.Projection')
@staticInterop
class Projection {
  external factory Projection(JSObject? opt_options);
}

extension ProjectionExtension on Projection {
  external JSString getCode();
  external JSObject getExtent();
  external JSObject getUnits();
  external JSNumber getMetersPerUnit();
  external JSObject getWorldExtent();
  external JSBoolean isGlobal();
  external void setGlobal(JSBoolean global);
  external void setExtent(JSObject extent);
  external void setWorldExtent(JSObject worldExtent);
  external void setGetPointResolution(JSObject func);
  external JSNumber getPointResolution(JSNumber resolution, JSObject point);
}

