// Generated by dartify

import 'dart:js_interop';

import 'reactnode.dart';

@JS('React.cloneElement')
external JSObject cloneElement(
  JSObject element,
  JSObject? props,
  JSArray<ReactNode> children,
);
