// Generated by dartify

import 'dart:js_interop';

import 'reactnode.dart';

@JS('React.Component')
@staticInterop
class Component {
  external factory Component(JSObject? opt_options);
}

extension ComponentExtension on Component {
  external JSObject get contextType;
  external set contextType(JSObject value);
  external JSObject get propTypes;
  external set propTypes(JSObject value);
  external JSObject get context;
  external set context(JSObject value);
  external void setState(JSObject state, JSObject? callback);
  external void forceUpdate(JSObject? callback);
  external ReactNode render();
  external JSObject get props;
  external JSObject get state;
  external set state(JSObject value);
}
