// Generated by dartify

import 'dart:js_interop';

import 'reactnode.dart';

@JS('React.createElement')
external JSObject createElement(
  JSObject type,
  JSObject? props,
  JSArray<ReactNode> children,
);
