// Generated by dartify

import 'dart:js_interop';

import 'dependencylist.dart';
import 'effectcallback.dart';

@JS('React.useEffect')
external void useEffect(EffectCallback effect, DependencyList? deps);
