// Generated by dartify

import 'dart:js_interop';

import 'dependencylist.dart';
import 'effectcallback.dart';

@JS('React.useInsertionEffect')
external void useInsertionEffect(EffectCallback effect, DependencyList? deps);
