// Generated by dartify

import 'dart:js_interop';

import 'dependencylist.dart';

@JS('React.useImperativeHandle')
external void useImperativeHandle(
  JSObject ref,
  JSObject init,
  DependencyList? deps,
);
