// Generated by dartify

import 'dart:js_interop';

import 'dependencylist.dart';
import 'effectcallback.dart';

@JS('React.useLayoutEffect')
external void useLayoutEffect(EffectCallback effect, DependencyList? deps);
