// Generated by dartify

import 'dart:js_interop';

import 'esrijsongeometry.dart';

@JS('ol.format.EsriJSON')
@staticInterop
class EsriJSON {
  external factory EsriJSON(JSObject? opt_options);
}

extension EsriJSONExtension on EsriJSON {
  external JSObject readFeature(JSObject source, JSObject? opt_options);
  external JSArray<JSObject> readFeatures(JSObject source, JSObject? opt_options);
  external JSObject readGeometry(JSObject source, JSObject? opt_options);
  external JSObject readProjection(JSObject source);
  external JSString writeGeometry(JSObject geometry, JSObject? opt_options);
  external EsriJSONGeometry writeGeometryObject(JSObject geometry, JSObject? opt_options);
  external JSString writeFeature(JSObject feature, JSObject? opt_options);
  external JSObject writeFeatureObject(JSObject feature, JSObject? opt_options);
  external JSString writeFeatures(JSArray<JSObject> features, JSObject? opt_options);
  external JSObject writeFeaturesObject(JSArray<JSObject> features, JSObject? opt_options);
}

