// Generated by dartify

import 'dart:js_interop';

import 'geojsonfeature.dart';
import 'geojsonfeaturecollection.dart';

@JS('ol.format.GeoJSON')
@staticInterop
class GeoJSON {
  external factory GeoJSON(JSObject? opt_options);
}

extension GeoJSONExtension on GeoJSON {
  external JSObject readFeature(JSObject source, JSObject? opt_options);
  external JSArray<JSObject> readFeatures(
    JSObject source,
    JSObject? opt_options,
  );
  external JSObject readGeometry(JSObject source, JSObject? opt_options);
  external JSObject readProjection(JSObject source);
  external JSString writeFeature(JSObject feature, JSObject? opt_options);
  external GeoJSONFeature writeFeatureObject(
    JSObject feature,
    JSObject? opt_options,
  );
  external JSString writeFeatures(
    JSArray<JSObject> features,
    JSObject? opt_options,
  );
  external GeoJSONFeatureCollection writeFeaturesObject(
    JSArray<JSObject> features,
    JSObject? opt_options,
  );
  external JSString writeGeometry(JSObject geometry, JSObject? opt_options);
  external JSObject writeGeometryObject(
    JSObject geometry,
    JSObject? opt_options,
  );
}
