// Generated by dartify

import 'dart:js_interop';

@JS('ol.format.GML')
@staticInterop
class GML {
  external factory GML(JSObject? opt_options);
}

extension GMLExtension on GML {
  external JSString writeFeatures(JSArray<JSObject> features, JSObject? opt_options);
  external JSObject writeFeaturesNode(JSArray<JSObject> features, JSObject? opt_options);
}

