// Generated by dartify

import 'dart:js_interop';

@JS('ol.format.GML3')
@staticInterop
class GML3 {
  external factory GML3(JSObject? opt_options);
}

extension GML3Extension on GML3 {
  external JSObject writeGeometryNode(JSObject geometry, JSObject? opt_options);
  external JSString writeFeatures(JSArray<JSObject> features, JSObject? opt_options);
  external JSObject writeFeaturesNode(JSArray<JSObject> features, JSObject? opt_options);
}

