// Generated by dartify

import 'dart:js_interop';

@JS('ol.format.GMLBase')
@staticInterop
class GMLBase {
  external factory GMLBase(JSObject? opt_options);
}

extension GMLBaseExtension on GMLBase {
  external JSArray<JSObject> readFeatures(JSObject source, JSObject? opt_options);
}

