// Generated by dartify

import 'dart:js_interop';

@JS('ol.format.GPX')
@staticInterop
class GPX {
  external factory GPX(JSObject? opt_options);
}

extension GPXExtension on GPX {
  external JSObject readFeature(JSObject source, JSObject? opt_options);
  external JSArray<JSObject> readFeatures(JSObject source, JSObject? opt_options);
  external JSObject readProjection(JSObject source);
  external JSString writeFeatures(JSArray<JSObject> features, JSObject? opt_options);
  external JSObject writeFeaturesNode(JSArray<JSObject> features, JSObject? opt_options);
}

