// Generated by dartify

import 'dart:js_interop';

@JS('ol.format.IGC')
@staticInterop
class IGC {
  external factory IGC(JSObject? opt_options);
}

extension IGCExtension on IGC {
  external JSObject readFeature(JSObject source, JSObject? opt_options);
  external JSArray<JSObject> readFeatures(JSObject source, JSObject? opt_options);
  external JSObject readProjection(JSObject source);
}

