// Generated by dartify

import 'dart:js_interop';

@JS('ol.format.KML')
@staticInterop
class KML {
  external factory KML(JSObject? opt_options);
}

extension KMLExtension on KML {
  external JSObject readFeature(JSObject source, JSObject? opt_options);
  external JSArray<JSObject> readFeatures(JSObject source, JSObject? opt_options);
  external JSString readName(JSObject source);
  external JSArray<JSObject> readNetworkLinks(JSObject source);
  external JSObject readProjection(JSObject source);
  external JSString writeFeatures(JSArray<JSObject> features, JSObject? opt_options);
  external JSObject writeFeaturesNode(JSArray<JSObject> features, JSObject? opt_options);
}

