// Generated by dartify

import 'dart:js_interop';

@JS('ol.format.MVT')
@staticInterop
class MVT {
  external factory MVT(JSObject? opt_options);
}

extension MVTExtension on MVT {
  external JSArray<JSObject> readFeatures(JSObject source, JSObject? opt_options);
  external JSObject readProjection(JSObject source);
  external void setLayers(JSArray<JSString> layers);
}

