// Generated by dartify

import 'dart:js_interop';

@JS('ol.format.OSMXML')
@staticInterop
class OSMXML {
  external factory OSMXML(JSObject? opt_options);
}

extension OSMXMLExtension on OSMXML {
  external JSArray<JSObject> readFeatures(JSObject source, JSObject? opt_options);
  external JSObject readProjection(JSObject source);
}

