// Generated by dartify

import 'dart:js_interop';

@JS('ol.format.Polyline')
@staticInterop
class Polyline {
  external factory Polyline(JSObject? opt_options);
}

extension PolylineExtension on Polyline {
  external JSString encodeDeltas(JSArray<JSNumber> numbers, JSNumber stride, JSNumber? opt_factor);
  external JSArray<JSNumber> decodeDeltas(JSString encoded, JSNumber stride, JSNumber? opt_factor);
  external JSString encodeFloats(JSArray<JSNumber> numbers, JSNumber? opt_factor);
  external JSArray<JSNumber> decodeFloats(JSString encoded, JSNumber? opt_factor);
  external JSObject readFeature(JSObject source, JSObject? opt_options);
  external JSArray<JSObject> readFeatures(JSObject source, JSObject? opt_options);
  external JSObject readGeometry(JSObject source, JSObject? opt_options);
  external JSObject readProjection(JSObject source);
  external JSString writeGeometry(JSObject geometry, JSObject? opt_options);
}

