// Generated by dartify

import 'dart:js_interop';

@JS('ol.format.TopoJSON')
@staticInterop
class TopoJSON {
  external factory TopoJSON(JSObject? opt_options);
}

extension TopoJSONExtension on TopoJSON {
  external JSArray<JSObject> readFeatures(JSObject source);
  external JSObject readProjection(JSObject object);
}

