// Generated by dartify

import 'dart:js_interop';

@JS('ol.format.WFS')
@staticInterop
class WFS {
  external factory WFS(JSObject? opt_options);
}

extension WFSExtension on WFS {
  external JSArray<JSObject> readFeatures(JSObject source, JSObject? opt_options);
  external JSObject readTransactionResponse(JSObject source);
  external JSObject readFeatureCollectionMetadata(JSObject source);
  external JSObject writeGetFeature(JSObject options);
  external JSObject writeTransaction(JSArray<JSObject> inserts, JSArray<JSObject> updates, JSArray<JSObject> deletes, JSObject options);
  external JSObject readProjection(JSObject source);
}

