// Generated by dartify

import 'dart:js_interop';

@JS('ol.format.WKT')
@staticInterop
class WKT {
  external factory WKT(JSObject? opt_options);
}

extension WKTExtension on WKT {
  external JSObject readFeature(JSObject source, JSObject? opt_options);
  external JSArray<JSObject> readFeatures(JSObject source, JSObject? opt_options);
  external JSObject readGeometry(JSObject source, JSObject? opt_options);
  external JSString writeFeature(JSObject feature, JSObject? opt_options);
  external JSString writeFeatures(JSArray<JSObject> features, JSObject? opt_options);
  external JSString writeGeometry(JSObject geometry);
}

