// Generated by dartify

import 'dart:js_interop';

@JS('ol.format.WMSCapabilities')
@staticInterop
class WMSCapabilities {
  external factory WMSCapabilities(JSObject? opt_options);
}

extension WMSCapabilitiesExtension on WMSCapabilities {
  external JSObject read(JSObject source);
}

