// Generated by dartify

import 'dart:js_interop';

@JS('ol.format.WMSGetFeatureInfo')
@staticInterop
class WMSGetFeatureInfo {
  external factory WMSGetFeatureInfo(JSObject? opt_options);
}

extension WMSGetFeatureInfoExtension on WMSGetFeatureInfo {
  external JSArray<JSObject> readFeatures(JSObject source, JSObject? opt_options);
}

