// Generated by dartify

import 'dart:js_interop';

@JS('ol.format.WMTSCapabilities')
@staticInterop
class WMTSCapabilities {
  external factory WMTSCapabilities(JSObject? opt_options);
}

extension WMTSCapabilitiesExtension on WMTSCapabilities {
  external JSObject read(JSObject source);
}

