// Generated by dartify

import 'dart:js_interop';

@JS('ol.layer.Base')
@staticInterop
class Base {
  external factory Base(JSObject? opt_options);
}

extension BaseExtension on Base {
  external JSObject getExtent();
  external JSNumber getMaxResolution();
  external JSNumber getMinResolution();
  external JSNumber getOpacity();
  external JSBoolean getVisible();
  external JSNumber getZIndex();
  external void setExtent(JSObject extent);
  external void setMaxResolution(JSNumber maxResolution);
  external void setMinResolution(JSNumber minResolution);
  external void setOpacity(JSNumber opacity);
  external void setVisible(JSBoolean visible);
  external void setZIndex(JSNumber zindex);
}

