// Generated by dartify

import 'dart:js_interop';

@JS('ol.layer.Group')
@staticInterop
class Group {
  external factory Group(JSObject? opt_options);
}

extension GroupExtension on Group {
  external JSObject getLayers();
  external void setLayers(JSObject layers);
}

