// Generated by dartify

import 'dart:js_interop';

@JS('ol.layer.Heatmap')
@staticInterop
class Heatmap {
  external factory Heatmap(JSObject? opt_options);
}

extension HeatmapExtension on Heatmap {
  external JSNumber getBlur();
  external JSArray<JSString> getGradient();
  external JSNumber getRadius();
  external void setBlur(JSNumber blur);
  external void setGradient(JSArray<JSString> colors);
  external void setRadius(JSNumber radius);
}

