// Generated by dartify

import 'dart:js_interop';

@JS('ol.layer.Tile')
@staticInterop
class Tile {
  external factory Tile(JSObject? opt_options);
}

extension TileExtension on Tile {
  external JSNumber getPreload();
  external void setPreload(JSNumber preload);
  external JSBoolean getUseInterimTilesOnError();
  external void setUseInterimTilesOnError(JSBoolean useInterimTilesOnError);
}

