// Generated by dartify

import 'dart:js_interop';

@JS('ol.layer.Vector')
@staticInterop
class Vector {
  external factory Vector(JSObject? opt_options);
}

extension VectorExtension on Vector {
  external JSObject getSource();
  external JSObject getStyle();
  external JSObject getStyleFunction();
  external void setStyle(JSObject style);
}

