// Generated by dartify

import 'dart:js_interop';

@JS('ol.layer.VectorTile')
@staticInterop
class VectorTile {
  external factory VectorTile(JSObject? opt_options);
}

extension VectorTileExtension on VectorTile {
  external JSNumber getPreload();
  external JSBoolean getUseInterimTilesOnError();
  external void setPreload(JSNumber preload);
  external void setUseInterimTilesOnError(JSBoolean useInterimTilesOnError);
}

