// Generated by dartify

import 'dart:js_interop';

import 'container.dart';
import 'root.dart';
import 'rootoptions.dart';

@JS('createRoot')
external Root createRoot(Container container, RootOptions? options);

