// Generated by dartify

import 'dart:js_interop';

@JS('ErrorInfo')
@staticInterop
class ErrorInfo {
  external factory ErrorInfo(JSObject? opt_options);
}

extension ErrorInfoExtension on ErrorInfo {
  external JSString get componentStack;
  external set componentStack(JSString value);
}

