// Generated by dartify

import 'dart:js_interop';

import 'hydrationoptions.dart';
import 'root.dart';

@JS('hydrateRoot')
external Root hydrateRoot(JSObject container, JSObject initialChildren, HydrationOptions? options);

