// Generated by dartify

import 'dart:js_interop';

@JS('HydrationOptions')
@staticInterop
class HydrationOptions {
  external factory HydrationOptions(JSObject? opt_options);
}

extension HydrationOptionsExtension on HydrationOptions {
  external JSObject get formState;
  external set formState(JSObject value);
  external JSString get identifierPrefix;
  external set identifierPrefix(JSString value);
  external JSObject get onUncaughtError;
  external set onUncaughtError(JSObject value);
  external JSObject get onRecoverableError;
  external set onRecoverableError(JSObject value);
  external JSObject get onCaughtError;
  external set onCaughtError(JSObject value);
}

