// Generated by dartify

import 'dart:js_interop';

@JS('ReactFormState')
@staticInterop
class ReactFormState {
  external factory ReactFormState(JSObject? opt_options);
}

extension ReactFormStateExtension on ReactFormState {
 
}

