// Generated by dartify

import 'dart:js_interop';

@JS('Root')
@staticInterop
class Root {
  external factory Root(JSObject? opt_options);
}

extension RootExtension on Root {
  external void render(JSObject children);
  external void unmount();
}

