// Generated by dartify

import 'dart:js_interop';

@JS('RootOptions')
@staticInterop
class RootOptions {
  external factory RootOptions(JSObject? opt_options);
}

extension RootOptionsExtension on RootOptions {
  external JSString get identifierPrefix;
  external set identifierPrefix(JSString value);
  external JSObject get onUncaughtError;
  external set onUncaughtError(JSObject value);
  external JSObject get onRecoverableError;
  external set onRecoverableError(JSObject value);
  external JSObject get onCaughtError;
  external set onCaughtError(JSObject value);
}

