// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.Modify.Event')
@staticInterop
class Event {
  external factory Event(JSObject? opt_options);
}

extension EventExtension on Event {
  external JSObject get features;
  external set features(JSObject value);
  external JSObject get mapBrowserEvent;
  external set mapBrowserEvent(JSObject value);
}

