// Generated by dartify

import 'dart:js_interop';

@JS('ol.style.Circle')
@staticInterop
class Circle {
  external factory Circle(JSObject? opt_options);
}

extension CircleExtension on Circle {
  external JSObject getFill();
  external JSObject getImage(JSNumber pixelRatio);
  external JSNumber getRadius();
  external JSObject getStroke();
  external void setRadius(JSNumber radius);
}

