// Generated by dartify

import 'dart:js_interop';

@JS('ol.style.Fill')
@staticInterop
class Fill {
  external factory Fill(JSObject? opt_options);
}

extension FillExtension on Fill {
  external JSObject getColor();
  external void setColor(JSObject color);
}

