// Generated by dartify

import 'dart:js_interop';

@JS('ol.style.Icon')
@staticInterop
class Icon {
  external factory Icon(JSObject? opt_options);
}

extension IconExtension on Icon {
  external JSArray<JSNumber> getAnchor();
  external JSObject getImage(JSNumber pixelRatio);
  external JSArray<JSNumber> getOrigin();
  external JSString getSrc();
  external JSObject getSize();
  external void load();
}

