// Generated by dartify

import 'dart:js_interop';

@JS('ol.style.Image')
@staticInterop
class Image {
  external factory Image(JSObject? opt_options);
}

extension ImageExtension on Image {
  external JSNumber getOpacity();
  external JSBoolean getRotateWithView();
  external JSNumber getRotation();
  external JSNumber getScale();
  external JSBoolean getSnapToPixel();
  external void setOpacity(JSNumber opacity);
  external void setRotation(JSNumber rotation);
  external void setScale(JSNumber scale);
}

