// Generated by dartify

import 'dart:js_interop';

@JS('ol.style.RegularShape')
@staticInterop
class RegularShape {
  external factory RegularShape(JSObject? opt_options);
}

extension RegularShapeExtension on RegularShape {
  external JSArray<JSNumber> getAnchor();
  external JSNumber getAngle();
  external JSObject getFill();
  external JSObject getImage(JSNumber pixelRatio);
  external JSArray<JSNumber> getOrigin();
  external JSNumber getPoints();
  external JSNumber getRadius();
  external JSNumber getRadius2();
  external JSObject getSize();
  external JSObject getStroke();
}

