// Generated by dartify

import 'dart:js_interop';

@JS('ol.style.Stroke')
@staticInterop
class Stroke {
  external factory Stroke(JSObject? opt_options);
}

extension StrokeExtension on Stroke {
  external JSObject getColor();
  external JSString getLineCap();
  external JSArray<JSNumber> getLineDash();
  external JSString getLineJoin();
  external JSNumber getMiterLimit();
  external JSNumber getWidth();
  external void setColor(JSObject color);
  external void setLineCap(JSString lineCap);
  external void setLineDash(JSArray<JSNumber> lineDash);
  external void setLineJoin(JSString lineJoin);
  external void setMiterLimit(JSNumber miterLimit);
  external void setWidth(JSNumber width);
}

