// Generated by dartify

import 'dart:js_interop';

@JS('ol.style.Text')
@staticInterop
class Text {
  external factory Text(JSObject? opt_options);
}

extension TextExtension on Text {
  external JSString getFont();
  external JSNumber getOffsetX();
  external JSNumber getOffsetY();
  external JSObject getFill();
  external JSBoolean getRotateWithView();
  external JSNumber getRotation();
  external JSNumber getScale();
  external JSObject getStroke();
  external JSString getText();
  external JSString getTextAlign();
  external JSString getTextBaseline();
  external void setFont(JSString font);
  external void setOffsetX(JSNumber offsetX);
  external void setOffsetY(JSNumber offsetY);
  external void setFill(JSObject fill);
  external void setRotation(JSNumber rotation);
  external void setScale(JSNumber scale);
  external void setStroke(JSObject stroke);
  external void setText(JSString text);
  external void setTextAlign(JSString textAlign);
  external void setTextBaseline(JSString textBaseline);
}

