// Generated by dartify

import 'dart:js_interop';

@JS('ol.AssertionError')
@staticInterop
class AssertionError {
  external factory AssertionError(JSObject? opt_options);
}

extension AssertionErrorExtension on AssertionError {
  external JSNumber get code;
  external set code(JSNumber value);
}

