// Generated by dartify

import 'dart:js_interop';

@JS('ol.Attribution')
@staticInterop
class Attribution {
  external factory Attribution(JSObject? opt_options);
}

extension AttributionExtension on Attribution {
  external JSString getHTML();
}

