// Generated by dartify

import 'dart:js_interop';

@JS('ol.Collection')
@staticInterop
class Collection {
  external factory Collection(JSObject? opt_options);
}

extension CollectionExtension on Collection {
  external void clear();
  external JSObject extend(JSArray<JSObject> arr);
  external void forEach(JSObject f, JSObject? opt_this);
  external JSArray<JSObject> getArray();
  external JSObject item(JSNumber index);
  external JSNumber getLength();
  external void insertAt(JSNumber index, JSObject elem);
  external JSObject pop();
  external JSNumber push(JSObject elem);
  external JSObject remove(JSObject elem);
  external JSObject removeAt(JSNumber index);
  external void setAt(JSNumber index, JSObject elem);
}

