// Generated by dartify

import 'dart:js_interop';

@JS('ol.DeviceOrientation')
@staticInterop
class DeviceOrientation {
  external factory DeviceOrientation(JSObject? opt_options);
}

extension DeviceOrientationExtension on DeviceOrientation {
  external JSNumber getAlpha();
  external JSNumber getBeta();
  external JSNumber getGamma();
  external JSNumber getHeading();
  external JSBoolean getTracking();
  external void setTracking(JSBoolean tracking);
}

