// Generated by dartify

import 'dart:js_interop';

@JS('ol.Feature')
@staticInterop
class Feature {
  external factory Feature(JSObject? opt_options);
}

extension FeatureExtension on Feature {
  external JSObject clone();
  external JSObject getGeometry();
  external JSObject getId();
  external JSString getGeometryName();
  external JSObject getStyle();
  external JSObject getStyleFunction();
  external void setGeometry(JSObject geometry);
  external void setStyle(JSObject style);
  external void setId(JSObject id);
  external void setGeometryName(JSString name);
}

