// Generated by dartify

import 'dart:js_interop';

@JS('ol.Geolocation')
@staticInterop
class Geolocation {
  external factory Geolocation(JSObject? opt_options);
}

extension GeolocationExtension on Geolocation {
  external JSNumber getAccuracy();
  external JSObject getAccuracyGeometry();
  external JSNumber getAltitude();
  external JSNumber getAltitudeAccuracy();
  external JSNumber getHeading();
  external JSObject getPosition();
  external JSObject getProjection();
  external JSNumber getSpeed();
  external JSBoolean getTracking();
  external JSObject getTrackingOptions();
  external void setProjection(JSObject projection);
  external void setTracking(JSBoolean tracking);
  external void setTrackingOptions(JSObject options);
}

