// Generated by dartify

import 'dart:js_interop';

@JS('ol.Graticule')
@staticInterop
class Graticule {
  external factory Graticule(JSObject? opt_options);
}

extension GraticuleExtension on Graticule {
  external JSObject getMap();
  external JSArray<JSObject> getMeridians();
  external JSArray<JSObject> getParallels();
  external void setMap(JSObject map);
}

