// Generated by dartify

import 'dart:js_interop';

@JS('ol.ImageTile')
@staticInterop
class ImageTile {
  external factory ImageTile(JSObject? opt_options);
}

extension ImageTileExtension on ImageTile {
  external JSObject getImage(JSObject? opt_context);
}

