// Generated by dartify

import 'dart:js_interop';

@JS('ol.Image')
@staticInterop
class Image {
  external factory Image(JSObject? opt_options);
}

extension ImageExtension on Image {
  external JSObject getImage(JSObject? opt_context);
  external void load();
}

