// Generated by dartify

import 'dart:js_interop';

@JS('ol.MapBrowserEvent')
@staticInterop
class MapBrowserEvent {
  external factory MapBrowserEvent(JSObject? opt_options);
}

extension MapBrowserEventExtension on MapBrowserEvent {
  external JSObject get originalEvent;
  external set originalEvent(JSObject value);
  external JSObject get pixel;
  external set pixel(JSObject value);
  external JSObject get coordinate;
  external set coordinate(JSObject value);
  external JSBoolean get dragging;
  external set dragging(JSBoolean value);
}

