// Generated by dartify

import 'dart:js_interop';

@JS('ol.MapBrowserPointerEvent')
@staticInterop
class MapBrowserPointerEvent {
  external factory MapBrowserPointerEvent(JSObject? opt_options);
}

extension MapBrowserPointerEventExtension on MapBrowserPointerEvent {
  external JSObject get pointerEvent;
  external set pointerEvent(JSObject value);
}

