// Generated by dartify

import 'dart:js_interop';

@JS('ol.MapEvent')
@staticInterop
class MapEvent {
  external factory MapEvent(JSObject? opt_options);
}

extension MapEventExtension on MapEvent {
  external JSObject get map;
  external set map(JSObject value);
  external JSObject get frameState;
  external set frameState(JSObject value);
}

