// Generated by dartify

import 'dart:js_interop';

@JS('ol.ObjectEvent')
@staticInterop
class ObjectEvent {
  external factory ObjectEvent(JSObject? opt_options);
}

extension ObjectEventExtension on ObjectEvent {
  external JSString get key;
  external set key(JSString value);
  external JSObject get oldValue;
  external set oldValue(JSObject value);
}

