// Generated by dartify

import 'dart:js_interop';

@JS('ol.Object')
@staticInterop
class Object {
  external factory Object(JSObject? opt_options);
}

extension ObjectExtension on Object {
  external JSObject get(JSString key);
  external JSArray<JSString> getKeys();
  external JSObject getProperties();
  external void set(JSString key, JSObject value, JSBoolean? opt_silent);
  external void setProperties(JSObject values, JSBoolean? opt_silent);
  external void unset(JSString key, JSBoolean? opt_silent);
}

