// Generated by dartify

import 'dart:js_interop';

@JS('ol.Observable')
@staticInterop
class Observable {
  external factory Observable(JSObject? opt_options);
}

extension ObservableExtension on Observable {
  external void unByKey(JSObject key);
  external void changed();
  external void dispatchEvent(JSObject event);
  external JSNumber getRevision();
  external JSObject on(JSObject type, JSObject listener, JSObject? opt_this);
  external JSObject once(JSObject type, JSObject listener, JSObject? opt_this);
  external void un(JSObject type, JSObject listener, JSObject? opt_this);
}

