// Generated by dartify

import 'dart:js_interop';

@JS('ol.Overlay')
@staticInterop
class Overlay {
  external factory Overlay(JSObject? opt_options);
}

extension OverlayExtension on Overlay {
  external JSObject getElement();
  external JSObject getId();
  external JSObject getMap();
  external JSArray<JSNumber> getOffset();
  external JSObject getPosition();
  external JSObject getPositioning();
  external void setElement(JSObject element);
  external void setMap(JSObject map);
  external void setOffset(JSArray<JSNumber> offset);
  external void setPosition(JSObject position);
  external void setPositioning(JSObject positioning);
}

