// Generated by dartify

import 'dart:js_interop';

@JS('ol.Sphere')
@staticInterop
class Sphere {
  external factory Sphere(JSObject? opt_options);
}

extension SphereExtension on Sphere {
  external JSNumber geodesicArea(JSArray<JSObject> coordinates);
  external JSNumber haversineDistance(JSObject c1, JSObject c2);
}

