// Generated by dartify

import 'dart:js_interop';

@JS('ol.VectorTile')
@staticInterop
class VectorTile {
  external factory VectorTile(JSObject? opt_options);
}

extension VectorTileExtension on VectorTile {
  external JSObject getFormat();
  external void setFeatures(JSArray<JSObject> features);
  external void setProjection(JSObject projection);
  external void setLoader(JSObject loader);
}

