// Generated by dartify

import 'dart:js_interop';

@JS('ol.View')
@staticInterop
class View {
  external factory View(JSObject? opt_options);
}

extension ViewExtension on View {
  external JSObject constrainCenter(JSObject center);
  external JSNumber constrainResolution(JSNumber resolution, JSNumber? opt_delta, JSNumber? opt_direction);
  external JSNumber constrainRotation(JSNumber rotation, JSNumber? opt_delta);
  external JSObject getCenter();
  external JSObject calculateExtent(JSObject size);
  external JSNumber getMaxResolution();
  external JSNumber getMinResolution();
  external JSObject getProjection();
  external JSNumber getResolution();
  external JSArray<JSNumber> getResolutions();
  external JSNumber getRotation();
  external JSNumber getZoom();
  external void fit(JSObject geometry, JSObject size, JSObject? opt_options);
  external void centerOn(JSObject coordinate, JSObject size, JSObject position);
  external void rotate(JSNumber rotation, JSObject? opt_anchor);
  external void setCenter(JSObject center);
  external void setResolution(JSNumber resolution);
  external void setRotation(JSNumber rotation);
  external void setZoom(JSNumber zoom);
  external void animate(JSObject var_args);
}

