// Generated by dartify

import 'dart:js_interop';

@JS('ol.control.Attribution')
@staticInterop
class Attribution {
  external factory Attribution(JSObject? opt_options);
}

extension AttributionExtension on Attribution {
  external void render(JSObject mapEvent);
  external JSBoolean getCollapsible();
  external void setCollapsible(JSBoolean collapsible);
  external void setCollapsed(JSBoolean collapsed);
  external JSBoolean getCollapsed();
}

