// Generated by dartify

import 'dart:js_interop';

@JS('ol.control.MousePosition')
@staticInterop
class MousePosition {
  external factory MousePosition(JSObject? opt_options);
}

extension MousePositionExtension on MousePosition {
  external void render(JSObject mapEvent);
  external JSObject getCoordinateFormat();
  external JSObject getProjection();
  external void setCoordinateFormat(JSObject format);
  external void setProjection(JSObject projection);
}

