// Generated by dartify

import 'dart:js_interop';

@JS('ol.control.OverviewMap')
@staticInterop
class OverviewMap {
  external factory OverviewMap(JSObject? opt_options);
}

extension OverviewMapExtension on OverviewMap {
  external void render(JSObject mapEvent);
  external JSBoolean getCollapsible();
  external void setCollapsible(JSBoolean collapsible);
  external void setCollapsed(JSBoolean collapsed);
  external JSBoolean getCollapsed();
  external JSObject getOverviewMap();
}

