// Generated by dartify

import 'dart:js_interop';

@JS('ol.control.Rotate')
@staticInterop
class Rotate {
  external factory Rotate(JSObject? opt_options);
}

extension RotateExtension on Rotate {
  external void render(JSObject mapEvent);
}

