// Generated by dartify

import 'dart:js_interop';

@JS('ol.control.ScaleLine')
@staticInterop
class ScaleLine {
  external factory ScaleLine(JSObject? opt_options);
}

extension ScaleLineExtension on ScaleLine {
  external JSObject getUnits();
  external void render(JSObject mapEvent);
  external void setUnits(JSObject units);
}

