// Generated by dartify

import 'dart:js_interop';

@JS('ol.control.ZoomSlider')
@staticInterop
class ZoomSlider {
  external factory ZoomSlider(JSObject? opt_options);
}

extension ZoomSliderExtension on ZoomSlider {
  external void render(JSObject mapEvent);
}

