// Generated by dartify

import 'dart:js_interop';

@JS('ol.tilegrid.WMTS')
@staticInterop
class WMTS {
  external factory WMTS(JSObject? opt_options);
}

extension WMTSExtension on WMTS {
  external JSArray<JSString> getMatrixIds();
  external JSObject createFromCapabilitiesMatrixSet(JSObject matrixSet, JSObject? opt_extent);
}

