// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.DoubleClickZoom')
@staticInterop
class DoubleClickZoom {
  external factory DoubleClickZoom(JSObject? opt_options);
}

extension DoubleClickZoomExtension on DoubleClickZoom {
  external JSBoolean handleEvent(JSObject mapBrowserEvent);
}

