// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.DragAndDrop')
@staticInterop
class DragAndDrop {
  external factory DragAndDrop(JSObject? opt_options);
}

extension DragAndDropExtension on DragAndDrop {
  external JSObject get handleEvent;
  external set handleEvent(JSObject value);
}

