// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.DragBox')
@staticInterop
class DragBox {
  external factory DragBox(JSObject? opt_options);
}

extension DragBoxExtension on DragBox {
  external JSObject getGeometry();
}

