// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.Draw')
@staticInterop
class Draw {
  external factory Draw(JSObject? opt_options);
}

extension DrawExtension on Draw {
  external void removeLastPoint();
  external void finishDrawing();
  external void extend(JSObject feature);
  external JSObject createRegularPolygon(JSNumber? opt_sides, JSNumber? opt_angle);
}

