// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.KeyboardZoom')
@staticInterop
class KeyboardZoom {
  external factory KeyboardZoom(JSObject? opt_options);
}

extension KeyboardZoomExtension on KeyboardZoom {
  external JSBoolean handleEvent(JSObject mapBrowserEvent);
}

