// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.KeyboardPan')
@staticInterop
class KeyboardPan {
  external factory KeyboardPan(JSObject? opt_options);
}

extension KeyboardPanExtension on KeyboardPan {
  external JSBoolean handleEvent(JSObject mapBrowserEvent);
}

