// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.Modify')
@staticInterop
class Modify {
  external factory Modify(JSObject? opt_options);
}

extension ModifyExtension on Modify {
  external JSBoolean removePoint();
}

