// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.MouseWheelZoom')
@staticInterop
class MouseWheelZoom {
  external factory MouseWheelZoom(JSObject? opt_options);
}

extension MouseWheelZoomExtension on MouseWheelZoom {
  external JSBoolean handleEvent(JSObject mapBrowserEvent);
  external void setMouseAnchor(JSBoolean useAnchor);
}

