// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.Pointer')
@staticInterop
class Pointer {
  external factory Pointer(JSObject? opt_options);
}

extension PointerExtension on Pointer {
  external JSBoolean handleEvent(JSObject mapBrowserEvent);
}

