// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.Select')
@staticInterop
class Select {
  external factory Select(JSObject? opt_options);
}

extension SelectExtension on Select {
  external JSObject getFeatures();
  external JSObject getLayer(JSObject feature);
  external JSBoolean handleEvent(JSObject mapBrowserEvent);
  external void setMap(JSObject map);
}

