// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.Snap')
@staticInterop
class Snap {
  external factory Snap(JSObject? opt_options);
}

extension SnapExtension on Snap {
  external void addFeature(JSObject feature, JSBoolean? opt_listen);
  external void removeFeature(JSObject feature, JSBoolean? opt_unlisten);
}

