// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.Translate')
@staticInterop
class Translate {
  external factory Translate(JSObject? opt_options);
}

extension TranslateExtension on Translate {
  external JSNumber getHitTolerance();
  external void setHitTolerance(JSNumber hitTolerance);
}

