// Generated by dartify

import 'dart:js_interop';

@JS('ol.render.Event')
@staticInterop
class Event {
  external factory Event(JSObject? opt_options);
}

extension EventExtension on Event {
  external JSObject get vectorContext;
  external set vectorContext(JSObject value);
  external JSObject get frameState;
  external set frameState(JSObject value);
  external JSObject get context;
  external set context(JSObject value);
  external JSObject get glContext;
  external set glContext(JSObject value);
}

