// Generated by dartify

import 'dart:js_interop';

@JS('ol.render.Feature')
@staticInterop
class Feature {
  external factory Feature(JSObject? opt_options);
}

extension FeatureExtension on Feature {
  external JSObject get(JSString key);
  external JSObject getExtent();
  external JSObject getGeometry();
  external JSObject getProperties();
  external JSObject getType();
}

