// Generated by dartify

import 'dart:js_interop';

@JS('ol.geom.Circle')
@staticInterop
class Circle {
  external factory Circle(JSObject? opt_options);
}

extension CircleExtension on Circle {
  external JSObject clone();
  external JSObject getCenter();
  external JSNumber getRadius();
  external JSObject getType();
  external JSBoolean intersectsExtent(JSObject extent);
  external void setCenter(JSObject center);
  external void setCenterAndRadius(JSObject center, JSNumber radius, JSObject? opt_layout);
  external void setRadius(JSNumber radius);
}

