// Generated by dartify

import 'dart:js_interop';

@JS('ol.geom.Geometry')
@staticInterop
class Geometry {
  external factory Geometry(JSObject? opt_options);
}

extension GeometryExtension on Geometry {
  external JSObject getClosestPoint(JSObject point, JSObject? opt_closestPoint);
  external JSBoolean intersectsCoordinate(JSObject coordinate);
  external JSObject getExtent(JSObject? opt_extent);
  external void rotate(JSNumber angle, JSObject anchor);
  external void scale(JSNumber sx, JSNumber? opt_sy, JSObject? opt_anchor);
  external JSObject simplify(JSNumber tolerance);
  external JSObject transform(JSObject source, JSObject destination);
  external JSObject getType();
}

