// Generated by dartify

import 'dart:js_interop';

@JS('ol.geom.GeometryCollection')
@staticInterop
class GeometryCollection {
  external factory GeometryCollection(JSObject? opt_options);
}

extension GeometryCollectionExtension on GeometryCollection {
  external JSObject clone();
  external JSArray<JSObject> getGeometries();
  external JSObject getType();
  external JSBoolean intersectsExtent(JSObject extent);
  external void setGeometries(JSArray<JSObject> geometries);
  external void applyTransform(JSObject transformFn);
  external void translate(JSNumber deltaX, JSNumber deltaY);
}

