// Generated by dartify

import 'dart:js_interop';

@JS('ol.geom.LineString')
@staticInterop
class LineString {
  external factory LineString(JSObject? opt_options);
}

extension LineStringExtension on LineString {
  external void appendCoordinate(JSObject coordinate);
  external JSObject clone();
  external JSObject forEachSegment(JSObject callback, JSObject? opt_this);
  external JSObject getCoordinateAtM(JSNumber m, JSBoolean? opt_extrapolate);
  external JSArray<JSObject> getCoordinates();
  external JSObject getCoordinateAt(JSNumber fraction, JSObject? opt_dest);
  external JSNumber getLength();
  external JSObject getType();
  external JSBoolean intersectsExtent(JSObject extent);
  external void setCoordinates(JSArray<JSObject> coordinates, JSObject? opt_layout);
}

