// Generated by dartify

import 'dart:js_interop';

@JS('ol.geom.LinearRing')
@staticInterop
class LinearRing {
  external factory LinearRing(JSObject? opt_options);
}

extension LinearRingExtension on LinearRing {
  external JSObject clone();
  external JSNumber getArea();
  external JSArray<JSObject> getCoordinates();
  external JSObject getType();
  external void setCoordinates(JSArray<JSObject> coordinates, JSObject? opt_layout);
}

