// Generated by dartify

import 'dart:js_interop';

@JS('ol.geom.MultiLineString')
@staticInterop
class MultiLineString {
  external factory MultiLineString(JSObject? opt_options);
}

extension MultiLineStringExtension on MultiLineString {
  external void appendLineString(JSObject lineString);
  external JSObject clone();
  external JSObject getCoordinateAtM(JSNumber m, JSBoolean? opt_extrapolate, JSBoolean? opt_interpolate);
  external JSArray<JSArray<JSObject>> getCoordinates();
  external JSObject getLineString(JSNumber index);
  external JSArray<JSObject> getLineStrings();
  external JSObject getType();
  external JSBoolean intersectsExtent(JSObject extent);
  external void setCoordinates(JSArray<JSArray<JSObject>> coordinates, JSObject? opt_layout);
}

