// Generated by dartify

import 'dart:js_interop';

@JS('ol.geom.MultiPoint')
@staticInterop
class MultiPoint {
  external factory MultiPoint(JSObject? opt_options);
}

extension MultiPointExtension on MultiPoint {
  external void appendPoint(JSObject point);
  external JSObject clone();
  external JSArray<JSObject> getCoordinates();
  external JSObject getPoint(JSNumber index);
  external JSArray<JSObject> getPoints();
  external JSObject getType();
  external JSBoolean intersectsExtent(JSObject extent);
  external void setCoordinates(JSArray<JSObject> coordinates, JSObject? opt_layout);
}

