// Generated by dartify

import 'dart:js_interop';

@JS('ol.geom.MultiPolygon')
@staticInterop
class MultiPolygon {
  external factory MultiPolygon(JSObject? opt_options);
}

extension MultiPolygonExtension on MultiPolygon {
  external void appendPolygon(JSObject polygon);
  external JSObject clone();
  external JSNumber getArea();
  external JSArray<JSArray<JSArray<JSObject>>> getCoordinates(JSBoolean? opt_right);
  external JSObject getInteriorPoints();
  external JSObject getPolygon(JSNumber index);
  external JSArray<JSObject> getPolygons();
  external JSObject getType();
  external JSBoolean intersectsExtent(JSObject extent);
  external void setCoordinates(JSArray<JSArray<JSArray<JSObject>>> coordinates, JSObject? opt_layout);
}

