// Generated by dartify

import 'dart:js_interop';

@JS('ol.geom.Point')
@staticInterop
class Point {
  external factory Point(JSObject? opt_options);
}

extension PointExtension on Point {
  external JSObject clone();
  external JSObject getCoordinates();
  external JSObject getType();
  external JSBoolean intersectsExtent(JSObject extent);
  external void setCoordinates(JSObject coordinates, JSObject? opt_layout);
}

