// Generated by dartify

import 'dart:js_interop';

@JS('ol.geom.Polygon')
@staticInterop
class Polygon {
  external factory Polygon(JSObject? opt_options);
}

extension PolygonExtension on Polygon {
  external void appendLinearRing(JSObject linearRing);
  external JSObject clone();
  external JSNumber getArea();
  external JSArray<JSArray<JSObject>> getCoordinates(JSBoolean? opt_right);
  external JSObject getInteriorPoint();
  external JSNumber getLinearRingCount();
  external JSObject getLinearRing(JSNumber index);
  external JSArray<JSObject> getLinearRings();
  external JSObject getType();
  external JSBoolean intersectsExtent(JSObject extent);
  external void setCoordinates(JSArray<JSArray<JSObject>> coordinates, JSObject? opt_layout);
  external JSObject circular(JSObject sphere, JSObject center, JSNumber radius, JSNumber? opt_n);
  external JSObject fromExtent(JSObject extent);
  external JSObject fromCircle(JSObject circle, JSNumber? opt_sides, JSNumber? opt_angle);
}

