// Generated by dartify

import 'dart:js_interop';

@JS('ol.geom.SimpleGeometry')
@staticInterop
class SimpleGeometry {
  external factory SimpleGeometry(JSObject? opt_options);
}

extension SimpleGeometryExtension on SimpleGeometry {
  external JSObject getFirstCoordinate();
  external JSObject getLastCoordinate();
  external JSObject getLayout();
  external void applyTransform(JSObject transformFn);
  external void translate(JSNumber deltaX, JSNumber deltaY);
}

