// Generated by dartify

import 'dart:js_interop';

@JS('ol.render.canvas.Immediate')
@staticInterop
class Immediate {
  external factory Immediate(JSObject? opt_options);
}

extension ImmediateExtension on Immediate {
  external void drawCircle(JSObject geometry);
  external void setStyle(JSObject style);
  external void drawGeometry(JSObject geometry);
  external void drawFeature(JSObject feature, JSObject style);
}

