// Generated by dartify

import 'dart:js_interop';

@JS('PdfPrinter')
@staticInterop
class PdfPrinter {
  external factory PdfPrinter(JSObject? opt_options);
}

extension PdfPrinterExtension on PdfPrinter {
  external JSObject createPdfKitDocument(JSObject docDefinition, JSObject? options);
}

