// Generated by dartify

import 'dart:js_interop';

import 'bufferoptions.dart';

@JS('TCreatedPdf')
@staticInterop
class TCreatedPdf {
  external factory TCreatedPdf();
}

extension TCreatedPdfExtension on TCreatedPdf {
  external void download(
      [JSObject? cbOrDefaultFileName, JSObject? cb, BufferOptions? options]);
  external void getBlob(JSObject cb, BufferOptions? options);
  external void getBase64(JSObject cb, BufferOptions? options);
  external void getBuffer(JSObject cb, BufferOptions? options);
  external void getDataUrl(JSObject cb, BufferOptions? options);
  external JSObject getStream(BufferOptions? options);
  external void open(BufferOptions? options, JSObject? win);
  external void print(BufferOptions? options, JSObject? win);
}
