// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.Draw.Event')
@staticInterop
class Event {
  external factory Event(JSObject? opt_options);
}

extension EventExtension on Event {
  external JSObject get feature;
  external set feature(JSObject value);
}

