// Generated by dartify

import 'dart:js_interop';

@JS('ol.Collection.Event')
@staticInterop
class Event {
  external factory Event(JSObject? opt_options);
}

extension EventExtension on Event {
  external JSObject get element;
  external set element(JSObject value);
}

