// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.Select.Event')
@staticInterop
class Event {
  external factory Event(JSObject? opt_options);
}

extension EventExtension on Event {
  external JSArray<JSObject> get selected;
  external set selected(JSArray<JSObject> value);
  external JSArray<JSObject> get deselected;
  external set deselected(JSArray<JSObject> value);
  external JSObject get mapBrowserEvent;
  external set mapBrowserEvent(JSObject value);
}

