// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.DragAndDrop.Event')
@staticInterop
class Event {
  external factory Event(JSObject? opt_options);
}

extension EventExtension on Event {
  external JSArray<JSObject> get features;
  external set features(JSArray<JSObject> value);
  external JSObject get file;
  external set file(JSObject value);
  external JSObject get projection;
  external set projection(JSObject value);
}

