// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.BingMaps')
@staticInterop
class BingMaps {
  external factory BingMaps(JSObject? opt_options);
}

extension BingMapsExtension on BingMaps {
  external JSObject get TOS_ATTRIBUTION;
  external set TOS_ATTRIBUTION(JSObject value);
}

