// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.CartoDB')
@staticInterop
class CartoDB {
  external factory CartoDB(JSObject? opt_options);
}

extension CartoDBExtension on CartoDB {
  external JSObject getConfig();
  external void updateConfig(JSObject config);
  external void setConfig(JSObject config);
}

