// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.Cluster')
@staticInterop
class Cluster {
  external factory Cluster(JSObject? opt_options);
}

extension ClusterExtension on Cluster {
  external JSObject getSource();
  external void setDistance(JSNumber distance);
}

