// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.ImageEvent')
@staticInterop
class ImageEvent {
  external factory ImageEvent(JSObject? opt_options);
}

extension ImageEventExtension on ImageEvent {
  external JSObject get image;
  external set image(JSObject value);
}

