// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.ImageVector')
@staticInterop
class ImageVector {
  external factory ImageVector(JSObject? opt_options);
}

extension ImageVectorExtension on ImageVector {
  external JSObject getSource();
  external JSObject getStyle();
  external JSObject getStyleFunction();
  external void setStyle(JSObject style);
}

