// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.ImageMapGuide')
@staticInterop
class ImageMapGuide {
  external factory ImageMapGuide(JSObject? opt_options);
}

extension ImageMapGuideExtension on ImageMapGuide {
  external JSObject getParams();
  external JSObject getImageLoadFunction();
  external void updateParams(JSObject params);
  external void setImageLoadFunction(JSObject imageLoadFunction);
}

