// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.ImageWMS')
@staticInterop
class ImageWMS {
  external factory ImageWMS(JSObject? opt_options);
}

extension ImageWMSExtension on ImageWMS {
  external JSString getGetFeatureInfoUrl(JSObject coordinate, JSNumber resolution, JSObject projection, JSObject params);
  external JSObject getParams();
  external JSObject getImageLoadFunction();
  external JSString getUrl();
  external void setImageLoadFunction(JSObject imageLoadFunction);
  external void setUrl(JSString url);
  external void updateParams(JSObject params);
}

