// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.ImageArcGISRest')
@staticInterop
class ImageArcGISRest {
  external factory ImageArcGISRest(JSObject? opt_options);
}

extension ImageArcGISRestExtension on ImageArcGISRest {
  external JSObject getParams();
  external JSObject getImageLoadFunction();
  external JSString getUrl();
  external void setImageLoadFunction(JSObject imageLoadFunction);
  external void setUrl(JSString url);
  external void updateParams(JSObject params);
}

