// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.OSM')
@staticInterop
class OSM {
  external factory OSM(JSObject? opt_options);
}

extension OSMExtension on OSM {
  external JSObject get ATTRIBUTION;
  external set ATTRIBUTION(JSObject value);
}

