// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.RasterEvent')
@staticInterop
class RasterEvent {
  external factory RasterEvent(JSObject? opt_options);
}

extension RasterEventExtension on RasterEvent {
  external JSObject get extent;
  external set extent(JSObject value);
  external JSNumber get resolution;
  external set resolution(JSNumber value);
  external JSObject get data;
  external set data(JSObject value);
}

