// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.Raster')
@staticInterop
class Raster {
  external factory Raster(JSObject? opt_options);
}

extension RasterExtension on Raster {
  external void setOperation(JSObject operation, JSObject? opt_lib);
}

