// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.TileUTFGrid')
@staticInterop
class TileUTFGrid {
  external factory TileUTFGrid(JSObject? opt_options);
}

extension TileUTFGridExtension on TileUTFGrid {
  external JSString getTemplate();
  external void forDataAtCoordinateAndResolution(JSObject coordinate, JSNumber resolution, JSObject callback, JSObject? opt_this, JSBoolean? opt_request);
}

