// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.Tile')
@staticInterop
class Tile {
  external factory Tile(JSObject? opt_options);
}

extension TileExtension on Tile {
  external JSObject getTileGrid();
}

