// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.TileEvent')
@staticInterop
class TileEvent {
  external factory TileEvent(JSObject? opt_options);
}

extension TileEventExtension on TileEvent {
  external JSObject get tile;
  external set tile(JSObject value);
}

