// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.TileImage')
@staticInterop
class TileImage {
  external factory TileImage(JSObject? opt_options);
}

extension TileImageExtension on TileImage {
  external void setRenderReprojectionEdges(JSBoolean render);
  external void setTileGridForProjection(JSObject projection, JSObject tilegrid);
}

