// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.TileJSON')
@staticInterop
class TileJSON {
  external factory TileJSON(JSObject? opt_options);
}

extension TileJSONExtension on TileJSON {
  external TileJSON getTileJSON();
}

