// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.TileArcGISRest')
@staticInterop
class TileArcGISRest {
  external factory TileArcGISRest(JSObject? opt_options);
}

extension TileArcGISRestExtension on TileArcGISRest {
  external JSObject getParams();
  external void updateParams(JSObject params);
}

