// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.TileWMS')
@staticInterop
class TileWMS {
  external factory TileWMS(JSObject? opt_options);
}

extension TileWMSExtension on TileWMS {
  external JSString getGetFeatureInfoUrl(JSObject coordinate, JSNumber resolution, JSObject projection, JSObject params);
  external JSObject getParams();
  external void updateParams(JSObject params);
}

