// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.UrlTile')
@staticInterop
class UrlTile {
  external factory UrlTile(JSObject? opt_options);
}

extension UrlTileExtension on UrlTile {
  external JSObject getTileLoadFunction();
  external JSObject getTileUrlFunction();
  external JSArray<JSString> getUrls();
  external void setTileLoadFunction(JSObject tileLoadFunction);
  external void setTileUrlFunction(JSObject tileUrlFunction, JSString? opt_key);
  external void setUrl(JSString url);
  external void setUrls(JSArray<JSString> urls);
}

