// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.VectorEvent')
@staticInterop
class VectorEvent {
  external factory VectorEvent(JSObject? opt_options);
}

extension VectorEventExtension on VectorEvent {
  external JSObject get feature;
  external set feature(JSObject value);
}

