// Generated by dartify

import 'dart:js_interop';

@JS('ol.source.WMTS')
@staticInterop
class WMTS {
  external factory WMTS(JSObject? opt_options);
}

extension WMTSExtension on WMTS {
  external JSObject getDimensions();
  external JSString getFormat();
  external JSString getLayer();
  external JSString getMatrixSet();
  external JSObject getRequestEncoding();
  external JSString getStyle();
  external JSString getVersion();
  external void updateDimensions(JSObject dimensions);
  external JSObject optionsFromCapabilities(JSObject wmtsCap, JSObject config);
}

