// Generated by dartify

import 'dart:js_interop';

@JS('ol.interaction.DragBox.Event')
@staticInterop
class Event {
  external factory Event(JSObject? opt_options);
}

extension EventExtension on Event {
  external JSObject get coordinate;
  external set coordinate(JSObject value);
  external JSObject get mapBrowserEvent;
  external set mapBrowserEvent(JSObject value);
}

